server:
  port : 8081
camunda.bpm.client:
  base-url: http://localhost:8080/engine-rest
  worker-id: workerSpringBootMultiThread
  date-format: yyyy-MM-dd'T'HH:mm:ss.SSSZ
  default-serialization-format: application/json